config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "transactions", to: "transactions#index"
  get "search", to: "pokemons#search", alias: :search
  resources :pokemons, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :transactions, only: [:new, :create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :pokemon_name, presence: true
  validates :level, presence: true, inclusion: { in: 1..100 }
  validates :level, numericality: { only_integer: true }
  validates :price, presence: true
  # validates :price, greater_than: 0
  validates :price, numericality: true
  # validates :description, presence: true

  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [:pokemon_name, :description],
    # Below is a dummy that doesn't work anyways because the two lists aren't linked per se
    # associated_against: {
    #   pokemon_list: [:name]
    # },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/pokemon_list.rb
class PokemonList < ApplicationRecord
  validates :name, uniqueness: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :pokemon
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :pokemons
  has_many :transactions

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :phone_number])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    # NOTE: order takes anything, objects or arrays alike
    @pokemons = Pokemon.all.where(sold: false).order("updated_at DESC")
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @transaction = Transaction.new
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @user = current_user
    @pokemon.user = @user
    # The below resets the pokedex number spat out from simpleform into the pokemon name again

    # if @pokemon.valid? && @pokemon.pokemon_name != "" && !@pokemon.price.nil? && @pokemon.address != ""
    if @pokemon.pokemon_name != "" && !@pokemon.price.nil? && @pokemon.address != "" && !@pokemon.level.nil?
      @pokemon.save
      @pokemon.pokemon_name = PokemonList.find(@pokemon.pokemon_name).name
      @pokemon.price = @pokemon.price.round(2)
      redirect_to pokemon_path(@pokemon)
    else
      render :new
    end
  end

  def edit
    @pokemon = Pokemon.find(params[:id])
  end

  def update
    @pokemon = Pokemon.find(params[:id])
    if @pokemon.user == current_user
      @pokemon.update(pokemon_params)
    else
      flash.alert = "You do not own the pokemon. Therefore, you cannot perform this action!"
    end
    redirect_to pokemon_path(@pokemon)
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    if @pokemon.user == current_user
      @pokemon.destroy
    else
      flash.alert = "You do not own the pokemon. Therefore, you cannot perform this action!"
    end
    redirect_to pokemons_path
  end

  def search
    if params[:query].present?
      # note that only the description is being searched now
      @pokemon_results = Pokemon.search_by_name_and_description(params[:query])
      # .where(sold: false).order("updated_at DESC")
      @pokemons = @pokemon_results
    else
      @pokemons = Pokemon.all.where(sold: false).order("updated_at DESC")
    end
      @markers = @pokemons.geocoded.map do |pokemon|
        {
          lat: pokemon.latitude,
          lng: pokemon.longitude,
          info_window: render_to_string(partial: "info_window", locals: { pokemon: pokemon }),
          image_url: helpers.asset_url("pokeball.png")
      }
      end
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:pokemon_id, :pokemon_name, :level, :description, :price, :address)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.all.order("updated_at DESC")
  end

  def new
    @pokemon = Pokemon.find(params[:pokemon_id])
    @user = current_user
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)
    @user = current_user
    @pokemon = Pokemon.find(params[:pokemon_id])
    @transaction.pokemon = @pokemon
    @transaction.user = @user

    if @transaction.save
      @pokemon.sold = true
      @pokemon.save
      redirect_to transactions_path
    else
      render :new
    end
  end

  private

  def transaction_params
    params.permit(:pokemon, :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <%= favicon_link_tag %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>

    <%= render 'shared/flashes' %>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-home-page">
<div class="text-home-page">
  <h1>Which Pokémon will lead you to victory?</h1>

<%= image_tag "https://mmos.com/wp-content/uploads/2021/07/pokemon-unite-key-art-banner.jpg", class: "img-home" %>

  <p>This is a platform where you can buy Pokémon to complete your team, and get yourself ready to compete in high elo competitions. </p>
  <ul>
  <p>The concept is really simple! You have 2 options:</p>
    <li class="home-list-items">You can buy Pokémon to build your team.</li>
    <li class="home-list-items">You're done fighting and you want to get money out of your time invested in the games.</li>
  </ul>
    <%= link_to "Buy a Pokémon", pokemons_path, class: "a-link-to buy" %>
    <%= link_to "Sell a Pokémon", new_pokemon_path, class: "a-link-to sell" %>
  </div>
  <div class="empty-div-home"></div>
</div>

app/views/pokemons/_form.html.erb
<div class="container-sell-form">
    <div class="container-form">
        <h3 class="title-form">Sell a Pokémon</h3>
        <%= simple_form_for [@user, @pokemon] do |f| %>
          <%= f.input :pokemon_name, collection: PokemonList.all, input_html: { class: "select2", style: "width: 100%"}, label_html: { class: "row justify-content-center"} %>
          <%= f.input :level, label_html: { class: "row justify-content-center"} %>
          <%= f.input :description, label_html: { class: "row justify-content-center"} %>
          <%= f.input :address, label_html: { class: "row justify-content-center"} %>
          <%= f.input :price, label_html: { class: "row justify-content-center"} %>
          <%= f.button :submit, 'Sell me now !', class: 'btn-submit' %>
        <% end %>
          <%= link_to pokemons_path do %>
            <ion-icon class="ionicon-icon" name="arrow-undo-outline"></ion-icon>
          <% end %>
    </div>
    <div class="container-form-img">

    </div>
</div>

app/views/pokemons/_info_window.html.erb
<div>
  <img src="<%= PokeApi.get(pokemon: pokemon.pokemon_name.downcase).sprites.front_default %>" alt="">
  <h4><%= pokemon.pokemon_name %></h4>
  <p>Level: <%= pokemon.level %></p>
  <p>Price: £<%= number_with_precision(pokemon.price, delimiter: ',', precision: 2) %></p>
</div>

app/views/pokemons/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
      <div class="add_pokemon">
        <h3>Edit a Pokémon</h3>
      </div>
    </div>
      <%= simple_form_for [@user, @pokemon] do |f| %>
        <%= f.input :pokemon_name, label_html: { class: "row justify-content-center"} %>
        <%= f.input :level, label_html: { class: "row justify-content-center"} %>
        <%= f.input :description, label_html: { class: "row justify-content-center"} %>
        <%= f.input :price, label_html: { class: "row justify-content-center"} %>
        <%= f.button :submit, 'Save Me', class: 'btn-black' %>
      <% end %>
  </div>
</div>



<%= link_to 'Back', pokemon_path %>

app/views/pokemons/index.html.erb
<div class="container-container">
  <div class="container-cards">
    <div class="pokemon-market-text">
      <h2>Pokémon currently available for purchase</h2>
    </div>

    <div style="width: 70%" class="index-search-bar">
      <%= form_tag search_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a Pokémon  by name or description"
        %>
        <%= submit_tag "Search", class: "d-none", remote: true %>
      <% end %>
    </div>

    <div class="pokemon-market-cards">
      <%@pokemons.each do |pokemon| %>
      <%= link_to pokemon_path(pokemon), class: "link_to_pkmn_show"  do %>
        <div class="card-container">
          <div class="card-pokemon">
            <img src="<%= PokeApi.get(pokemon: pokemon.pokemon_name.downcase).sprites.front_default %>" alt="">
          </div>

          <div class="card-description">
            <h4><%= pokemon.pokemon_name %></h4>
            <p class="index-cards-descriptions"><%= pokemon.description %></p>
            <p>£<%= number_with_precision(pokemon.price, delimiter: ',', precision: 2) %></p>
            <p> </p>
          </div>

        </div>
        <% end %>
        <% end %>
  </div>
</div>

app/views/pokemons/new.html.erb
<%= render 'form', pokemon: @pokemon %>

app/views/pokemons/search.html.erb
  <div class="container-cards">
    <div class="pokemon-market-text">
      <h2>Here are all the Pokémons you can buy</h2>
    </div>

    <div style="width: 80%">
      <%= form_tag search_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a Pokémon  by name or description"
        %>
        <%= submit_tag "Search", class: "d-none" %>
      <% end %>
    </div>

    <div class="pokemon-market-cards">
      <%@pokemons.each do |pokemon| %>
      <%= link_to pokemon_path(pokemon), class: "link_to_pkmn_show"  do %>
        <div class="card-container">
          <div class="card-pokemon">
            <img src="<%= PokeApi.get(pokemon: pokemon.pokemon_name.downcase).sprites.front_default %>" alt="">
          </div>

          <div class="card-description">
            <h4><%= pokemon.pokemon_name %></h4>
            <p class="index-cards-descriptions"><%= pokemon.description %></p>
            <p>£<%= number_with_precision(pokemon.price, delimiter: ',', precision: 2) %></p>
            <p> </p>
          </div>

        </div>
        <% end %>
        <% end %>
    </div>

    <div id="map" style="width: 75%; height: 500px;"
      data-controller="mapbox"
      data-mapbox-markers-value="<%= @markers.to_json %>"
      data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

</div>

app/views/pokemons/show.html.erb
<div id="cards">
  <figure class="card card--dark">
    <div class="card__image-container">
      <img src="<%= PokeApi.get(pokemon: @pokemon.pokemon_name.downcase).sprites.front_default %>" alt="Pokemon" class="card__image">
    </div>

    <figcaption class="card__caption">
      <h2 class="card__name"><%= @pokemon.pokemon_name %></h2>

      <table class="card__stats">
        <tbody><tr>
          <th>Level:</th>
          <td><%= @pokemon.level %></td>
        </tr>

        <tr>
          <th>Price:</th>
          <td>£ <%= number_with_precision(@pokemon.price, delimiter: ',', precision: 2) %></td>
        </tr>


      </table>
      <div class="card__description">
        <p>Description: <%= @pokemon.description%></p>
      </div>
    </figcaption>
  </figure>

  <div class="cta-show">
    <%= link_to "Buy Pokémon", new_pokemon_transaction_path([@pokemon, current_user]), class: "a-link-to buy btn-submit", "data-toggle" => "modal", "data-target" => "#exampleModal" %>
    <%= link_to pokemons_path do %>
      <ion-icon class="ionicon-icon back-icon" name="arrow-undo-outline"></ion-icon>
    <% end %>
  </div>
</div>


<%# link_to "Remove", pokemon_path(@pokemon), class: "btn-submit", method: :delete, data: { confirm: "Are you sure?" } %>
<%# link_to 'Edit', edit_pokemon_path, class: "btn-submit" %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">  </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <h2 class="text-modal" >Are you sure you want to buy this Pokémon ?</h2>
        <img src="<%= PokeApi.get(pokemon: @pokemon.pokemon_name.downcase).sprites.front_default %>" alt="Pokemon" class="card__image">
       <h3 class="text-modal"><%= @pokemon.pokemon_name %> (level: <%= @pokemon.level %>) for £<%= number_with_precision(@pokemon.price, delimiter: ',', precision: 2) %> </h3>
      </div>
      <div class="modal-footer d-flex justify-content-center">
        <p>
        <%= simple_form_for [@pokemon, @transaction] do |f| %>
          <%= f.submit "Buy now", class: "a-link-to btn-submit" %>
        <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
<%= image_tag("https://www.freepnglogos.com/uploads/black-pokemon-logo-transparent-27.png", alt: 'Site Logo', class: "logo")  %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Transactions", transactions_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Buy Pokémon", pokemons_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sell Pokémon", new_pokemon_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://icon-library.com/images/pikachu-png-icon/pikachu-png-icon-0.jpg", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Change personal info", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item navbar-collapse">
          <%= link_to "Login", new_user_session_path, class: "nav-link btn-ghost" %>
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link btn-ghost" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="container-transactions">
  <h2>Here are all completed transactions</h2>

  <div class="img-all-transactions">
  </div>

  <h2>See which Pokémon are trending and prepare a counter strategy</h2>

  <table>
    <tr>
      <th>Transaction</th>
      <th>Bought by</th>
      <th>Sold by</th>
      <th>Pokémon</th>
      <th>Price</th>
    </tr>

    <% counter = 1 %>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= counter  %></td>
        <td><%= transaction.user.first_name %></td>
        <td><%= transaction.pokemon.user.first_name %></td>
        <td><%= transaction.pokemon.pokemon_name %></td>
        <td>£ <%= number_with_precision(transaction.pokemon.price, delimiter: ',', precision: 2) %></td>
        <% counter += 1 %>
      </tr>
    <% end %>

  </table>
</div>